import { Ionicons } from '@expo/vector-icons';
import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View, ViewStyle } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors } from '@/constants/theme';

export function Screen({children,scroll=true,style}:{children:React.ReactNode;scroll?:boolean;style?:ViewStyle}){
  const body=scroll?<ScrollView contentContainerStyle={[styles.content,style]} keyboardShouldPersistTaps="handled">{children}</ScrollView>:<View style={[styles.content,{flex:1},style]}>{children}</View>;
  return <SafeAreaView style={styles.safe}>{body}</SafeAreaView>;
}
export function Logo({light=false,compact=false}:{light?:boolean;compact?:boolean}){return <View style={styles.logoRow}><View style={[styles.logoBox,compact&&{width:38,height:38,borderRadius:12}]}><Text style={[styles.logoK,compact&&{fontSize:27}]}>K</Text></View><View><Text style={[styles.logoName,{color:light?colors.white:colors.black},compact&&{fontSize:20}]}>Karibu</Text><Text style={styles.logoSub}>FOR SCHOOLS</Text></View></View>}
export function Header({title,subtitle,back,onBack,right}:{title:string;subtitle?:string;back?:boolean;onBack?:()=>void;right?:React.ReactNode}){return <View style={styles.header}>{back?<Pressable onPress={onBack} style={styles.back}><Ionicons name="arrow-back" size={23}/></Pressable>:null}<View style={{flex:1}}><Text style={styles.headerTitle}>{title}</Text>{subtitle?<Text style={styles.headerSub}>{subtitle}</Text>:null}</View>{right}</View>}
export function Card({children,style}:{children:React.ReactNode;style?:ViewStyle}){return <View style={[styles.card,style]}>{children}</View>}
export function Button({label,onPress,variant='red',disabled=false}:{label:string;onPress?:()=>void;variant?:'red'|'black'|'outline'|'yellow';disabled?:boolean}){const bg=variant==='red'?colors.red:variant==='black'?colors.black:variant==='yellow'?colors.yellow:colors.white; const fg=variant==='yellow'||variant==='outline'?colors.black:colors.white; return <Pressable disabled={disabled} onPress={onPress} style={({pressed})=>[styles.button,{backgroundColor:bg,borderWidth:variant==='outline'?1:0,borderColor:colors.border,opacity: disabled ? 0.45 : pressed ? 0.82 : 1}]}><Text style={[styles.buttonText,{color:fg}]}>{label}</Text></Pressable>}
export function Section({title,action}:{title:string;action?:string}){return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{action?<Text style={styles.action}>{action}</Text>:null}</View>}
export function Row({icon,title,subtitle,onPress,right}:{icon?:any;title:string;subtitle?:string;onPress?:()=>void;right?:React.ReactNode}){return <Pressable onPress={onPress} style={({pressed})=>[styles.row,pressed&&onPress?{opacity:.65}:null]}>{icon?<View style={styles.rowIcon}><Ionicons name={icon} size={22}/></View>:null}<View style={{flex:1}}><Text style={styles.rowTitle}>{title}</Text>{subtitle?<Text style={styles.rowSub}>{subtitle}</Text>:null}</View>{right??(onPress?<Ionicons name="chevron-forward" size={20} color={colors.muted}/>:null)}</Pressable>}
export function Pill({label,tone='green'}:{label:string;tone?:'green'|'red'|'yellow'|'black'}){const bg=tone==='green'?colors.paleGreen:tone==='red'?colors.paleRed:tone==='yellow'?colors.paleYellow:'#ECECEF'; const fg=tone==='green'?colors.green:tone==='red'?colors.red:tone==='yellow'?colors.amber:colors.black; return <View style={[styles.pill,{backgroundColor:bg}]}><Text style={{color:fg,fontSize:11,fontWeight:'900'}}>{label}</Text></View>}
export function Money({value,style}:{value:number;style?:any}){return <Text style={style}>UGX {value.toLocaleString('en-GB')}</Text>}
export function Stat({label,value,helper,tone='white'}:{label:string;value:string;helper:string;tone?:'white'|'black'}){return <Card style={[styles.stat,tone==='black'?{backgroundColor:colors.black,borderColor:colors.black}:null]}><Text style={[styles.statLabel,tone==='black'?{color:'#CFCFD2'}:null]}>{label}</Text><Text style={[styles.statValue,tone==='black'?{color:colors.white}:null]}>{value}</Text><Text style={[styles.statHelper,tone==='black'?{color:'#CFCFD2'}:null]}>{helper}</Text></Card>}
export function Progress({value}:{value:number}){return <View style={styles.progressTrack}><View style={[styles.progressFill,{width:`${Math.max(0,Math.min(100,value))}%`}]} /></View>}

const styles=StyleSheet.create({
 safe:{flex:1,backgroundColor:colors.background},content:{padding:18,paddingBottom:36},
 logoRow:{flexDirection:'row',alignItems:'center',gap:10},logoBox:{width:54,height:54,borderRadius:17,backgroundColor:colors.yellow,alignItems:'center',justifyContent:'center'},logoK:{fontSize:39,fontWeight:'900',color:colors.red},logoName:{fontSize:27,fontWeight:'900'},logoSub:{alignSelf:'flex-start',backgroundColor:colors.red,color:colors.white,borderRadius:999,paddingHorizontal:8,paddingVertical:3,fontSize:8,fontWeight:'900',letterSpacing:1.2},
 header:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:18},back:{width:42,height:42,borderRadius:14,backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},headerTitle:{fontSize:27,fontWeight:'900'},headerSub:{color:colors.muted,marginTop:3},
 card:{backgroundColor:colors.card,borderRadius:20,padding:16,borderWidth:1,borderColor:colors.border},button:{minHeight:54,borderRadius:16,alignItems:'center',justifyContent:'center',paddingHorizontal:16},buttonText:{fontSize:16,fontWeight:'900'},
 section:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:24,marginBottom:11},sectionTitle:{fontSize:19,fontWeight:'900'},action:{color:colors.red,fontWeight:'800'},
 row:{flexDirection:'row',alignItems:'center',gap:12,minHeight:67,paddingVertical:11,borderBottomWidth:1,borderBottomColor:colors.border},rowIcon:{width:44,height:44,borderRadius:14,backgroundColor:colors.paleYellow,alignItems:'center',justifyContent:'center'},rowTitle:{fontSize:15,fontWeight:'900'},rowSub:{color:colors.muted,fontSize:12,marginTop:4,lineHeight:17},
 pill:{borderRadius:999,paddingHorizontal:10,paddingVertical:6},stat:{flex:1,minHeight:126},statLabel:{color:colors.muted,fontSize:12},statValue:{fontSize:24,fontWeight:'900',marginTop:8},statHelper:{color:colors.muted,fontSize:11,marginTop:7,lineHeight:16},
 progressTrack:{height:9,borderRadius:999,backgroundColor:'#ECECEF',overflow:'hidden'},progressFill:{height:'100%',backgroundColor:colors.red,borderRadius:999}
});
